/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MDIForm.java
 *
 * Created on Dec 3, 2010, 8:57:04 AM
 */

package hospital;

/**
 *
 * @author Student
 */
public class MDIForm extends javax.swing.JFrame {

    /** Creates new form MDIForm */
    public MDIForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuadd = new javax.swing.JMenu();
        menupt = new javax.swing.JMenuItem();
        menuempl = new javax.swing.JMenuItem();
        menuroom = new javax.swing.JMenuItem();
        menubill = new javax.swing.JMenuItem();
        menupdate = new javax.swing.JMenu();
        menueptd = new javax.swing.JMenuItem();
        menueempl = new javax.swing.JMenuItem();
        menueroom = new javax.swing.JMenuItem();
        menuebill = new javax.swing.JMenuItem();
        menudelpt = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menudelempl = new javax.swing.JMenuItem();
        menudelroom = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menuviewpt = new javax.swing.JMenuItem();
        menuviewempl = new javax.swing.JMenuItem();
        menuviewroom = new javax.swing.JMenuItem();
        menuviewbill = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuabtus = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        menuadd.setText("Add Details");

        menupt.setText("AddPatientDetails");
        menupt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuptActionPerformed(evt);
            }
        });
        menuadd.add(menupt);

        menuempl.setText("Add DoctorDetails");
        menuempl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuemplActionPerformed(evt);
            }
        });
        menuadd.add(menuempl);

        menuroom.setText("AddRoomDetails ");
        menuroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuroomActionPerformed(evt);
            }
        });
        menuadd.add(menuroom);

        menubill.setText("AddBillDetails");
        menubill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubillActionPerformed(evt);
            }
        });
        menuadd.add(menubill);

        menuBar.add(menuadd);

        menupdate.setText("Updates");

        menueptd.setText("EditPatientsDetails");
        menueptd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueptdActionPerformed(evt);
            }
        });
        menupdate.add(menueptd);

        menueempl.setText("EditDoctorsDetail");
        menueempl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueemplActionPerformed(evt);
            }
        });
        menupdate.add(menueempl);

        menueroom.setText("EditRoomDetails");
        menueroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueroomActionPerformed(evt);
            }
        });
        menupdate.add(menueroom);

        menuebill.setText("EditBillDetails");
        menuebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuebillActionPerformed(evt);
            }
        });
        menupdate.add(menuebill);

        menudelpt.setText("DeletePatientsDetails");
        menudelpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudelptActionPerformed(evt);
            }
        });
        menupdate.add(menudelpt);
        menupdate.add(jSeparator1);

        menudelempl.setText("DeleteDoctorsDetails");
        menudelempl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudelemplActionPerformed(evt);
            }
        });
        menupdate.add(menudelempl);

        menudelroom.setText("DeleteRoomDetails");
        menupdate.add(menudelroom);

        menuBar.add(menupdate);

        helpMenu.setText("View");

        menuviewpt.setText("PatientsDetails");
        menuviewpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewptActionPerformed(evt);
            }
        });
        helpMenu.add(menuviewpt);

        menuviewempl.setText("DoctorDetails");
        menuviewempl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewemplActionPerformed(evt);
            }
        });
        helpMenu.add(menuviewempl);

        menuviewroom.setText("RoomDetails");
        menuviewroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewroomActionPerformed(evt);
            }
        });
        helpMenu.add(menuviewroom);

        menuviewbill.setText("BillDetails");
        menuviewbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewbillActionPerformed(evt);
            }
        });
        helpMenu.add(menuviewbill);

        menuBar.add(helpMenu);

        jMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("Help");

        menuabtus.setText("AboutUs");
        menuabtus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuabtusActionPerformed(evt);
            }
        });
        jMenu1.add(menuabtus);

        jMenuItem1.setText("Contents");
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        jMenu2.setText("Exit");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuroomActionPerformed
        AddRoomDetails r1 = new AddRoomDetails();
        desktopPane.add(r1);
         r1.setVisible(true);
}//GEN-LAST:event_menuroomActionPerformed

    private void menuptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuptActionPerformed
       AddPatientsDetails p1= new AddPatientsDetails();
       desktopPane.add(p1);
       p1.setVisible(true);
    }//GEN-LAST:event_menuptActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void menuemplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuemplActionPerformed
       AddDoctorDetails e1= new AddDoctorDetails();
       desktopPane.add(e1);
       e1.setVisible(true);
    }//GEN-LAST:event_menuemplActionPerformed

    private void menubillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubillActionPerformed
        AddBillDetails b1 = new AddBillDetails();
        desktopPane.add(b1);
        b1.setVisible(true);
    }//GEN-LAST:event_menubillActionPerformed

    private void menueemplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueemplActionPerformed
       EditDoctorDetails n1 = new EditDoctorDetails();
       desktopPane.add(n1);
       n1.setVisible(true);
    }//GEN-LAST:event_menueemplActionPerformed

    private void menueptdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueptdActionPerformed
      EditPatientsDetails f1 = new EditPatientsDetails();
       desktopPane.add(f1);
       f1.setVisible(true);
    }//GEN-LAST:event_menueptdActionPerformed

    private void menueroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueroomActionPerformed
         EditRoomDetails j1 = new EditRoomDetails();
       desktopPane.add(j1);
       j1.setVisible(true);
    }//GEN-LAST:event_menueroomActionPerformed

    private void menuebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuebillActionPerformed
       EditBillDetails d1 = new EditBillDetails();
       desktopPane.add(d1);
       d1.setVisible(true);
    }//GEN-LAST:event_menuebillActionPerformed

    private void menudelemplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudelemplActionPerformed
         DeleteDoctorDetails o1 = new DeleteDoctorDetails();
       desktopPane.add(o1);
       o1.setVisible(true);
    }//GEN-LAST:event_menudelemplActionPerformed

    private void menudelptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudelptActionPerformed
       DeletePatientsDetails t1 = new DeletePatientsDetails();
       desktopPane.add(t1);
       t1.setVisible(true);
    }//GEN-LAST:event_menudelptActionPerformed

    private void menuviewptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewptActionPerformed
      PatientDetails h1 = new PatientDetails();
       desktopPane.add(h1);
       h1.setVisible(true);
    }//GEN-LAST:event_menuviewptActionPerformed

    private void menuviewemplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewemplActionPerformed
       DoctorDetails k1 = new DoctorDetails();
       desktopPane.add(k1);
       k1.setVisible(true);
    }//GEN-LAST:event_menuviewemplActionPerformed

    private void menuviewroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewroomActionPerformed
       RoomDetails w1 = new RoomDetails();
       desktopPane.add(w1);
       w1.setVisible(true);
    }//GEN-LAST:event_menuviewroomActionPerformed

    private void menuviewbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewbillActionPerformed
      BillDetails d1 = new BillDetails();
       desktopPane.add(d1);
       d1.setVisible(true);
    }//GEN-LAST:event_menuviewbillActionPerformed

    private void menuabtusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuabtusActionPerformed
     AboutUs g1 = new AboutUs();
       desktopPane.add(g1);
       g1.setVisible(true);
    }//GEN-LAST:event_menuabtusActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuabtus;
    private javax.swing.JMenu menuadd;
    private javax.swing.JMenuItem menubill;
    private javax.swing.JMenuItem menudelempl;
    private javax.swing.JMenuItem menudelpt;
    private javax.swing.JMenuItem menudelroom;
    private javax.swing.JMenuItem menuebill;
    private javax.swing.JMenuItem menueempl;
    private javax.swing.JMenuItem menuempl;
    private javax.swing.JMenuItem menueptd;
    private javax.swing.JMenuItem menueroom;
    private javax.swing.JMenu menupdate;
    private javax.swing.JMenuItem menupt;
    private javax.swing.JMenuItem menuroom;
    private javax.swing.JMenuItem menuviewbill;
    private javax.swing.JMenuItem menuviewempl;
    private javax.swing.JMenuItem menuviewpt;
    private javax.swing.JMenuItem menuviewroom;
    // End of variables declaration//GEN-END:variables

}
